[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/deriva-corsa/*"
  to = "/deriva-corsa/index.html"
  status = 200

[[redirects]]
  from = "/numerical-fly*"
  to = "/numerical-fly"
  status = 200